import { Task } from "./tasks/task/task.model";

export const DUMMY_TASKS: Task[] = [
  {
    id: 't1',
    userId: 'u1',
    title: 'Master Angular',
    summary:
      'Learn all the basic and advanced features of Angular & how to apply them.',
    dueDate: '2025-12-31',
  },
  {
    id: 't2',
    userId: 'u3',
    title: 'Build first prototype',
    summary: 'Build a first prototype of the online shop website',
    dueDate: '2024-05-31',
  },
  {
    id: 't3',
    userId: 'u3',
    title: 'Prepare issue template',
    summary:
      'Prepare and describe an issue template which will help with project management',
    dueDate: '2024-06-15',
  },
  {
    id: 't4',
    userId: 'u2',
    title: 'Design user interface',
    summary: 'Create wireframes and mockups for the new dashboard interface',
    dueDate: '2024-07-10',
  },
  {
    id: 't5',
    userId: 'u5',
    title: 'Set up CI/CD pipeline',
    summary:
      'Configure continuous integration and continuous deployment for the project',
    dueDate: '2024-08-01',
  },
  {
    id: 't6',
    userId: 'u4',
    title: 'Write API documentation',
    summary: 'Document all endpoints and usage of the new API',
    dueDate: '2024-09-20',
  },
  {
    id: 't7',
    userId: 'u1',
    title: 'Refactor authentication module',
    summary: 'Improve security and performance of the authentication module',
    dueDate: '2024-10-15',
  },
  {
    id: 't8',
    userId: 'u6',
    title: 'Conduct user research',
    summary: 'Collect feedback from users on the current application',
    dueDate: '2024-11-30',
  },
  {
    id: 't9',
    userId: 'u2',
    title: 'Implement payment gateway',
    summary: 'Integrate a payment processing system into the website',
    dueDate: '2024-12-05',
  },
  {
    id: 't10',
    userId: 'u3',
    title: 'Update project plan',
    summary: 'Revise and update the project plan according to new requirements',
    dueDate: '2024-07-20',
  },
  {
    id: 't11',
    userId: 'u4',
    title: 'Review codebase',
    summary: 'Perform a thorough review of the codebase for improvements',
    dueDate: '2024-08-15',
  },
  {
    id: 't12',
    userId: 'u5',
    title: 'Optimize database queries',
    summary: 'Improve the efficiency of database queries and indexing',
    dueDate: '2024-09-10',
  },
  {
    id: 't13',
    userId: 'u6',
    title: 'Create marketing plan',
    summary: 'Develop a comprehensive marketing plan for the product launch',
    dueDate: '2024-10-05',
  },
  {
    id: 't14',
    userId: 'u1',
    title: 'Review user feedback',
    summary: 'Analyze and address user feedback from the latest release',
    dueDate: '2024-11-15',
  },
  {
    id: 't15',
    userId: 'u2',
    title: 'Draft project proposal',
    summary: 'Prepare a proposal for the next phase of the project',
    dueDate: '2024-12-20',
  },
  {
    id: 't16',
    userId: 'u3',
    title: 'Setup analytics',
    summary: 'Implement analytics tracking for user engagement and behavior',
    dueDate: '2024-07-25',
  },
  {
    id: 't17',
    userId: 'u4',
    title: 'Conduct team meeting',
    summary:
      'Organize and lead a meeting to discuss project progress and issues',
    dueDate: '2024-08-25',
  },
  {
    id: 't18',
    userId: 'u5',
    title: 'Implement search functionality',
    summary:
      'Add search capability to the application for better user experience',
    dueDate: '2024-09-30',
  },
  {
    id: 't19',
    userId: 'u6',
    title: 'Create user onboarding guide',
    summary:
      'Develop a guide to help new users get started with the application',
    dueDate: '2024-10-20',
  },
  {
    id: 't20',
    userId: 'u1',
    title: 'Set up user roles and permissions',
    summary:
      'Define and implement different user roles and their permissions in the app',
    dueDate: '2024-11-10',
  },
  {
    id: 't21',
    userId: 'u2',
    title: 'Conduct performance testing',
    summary: 'Test the application’s performance under various conditions',
    dueDate: '2024-12-01',
  },
  {
    id: 't22',
    userId: 'u3',
    title: 'Update user interface',
    summary: 'Enhance the design and usability of the user interface',
    dueDate: '2024-06-30',
  },
  {
    id: 't23',
    userId: 'u4',
    title: 'Prepare for product launch',
    summary: 'Finalize all preparations for the upcoming product launch event',
    dueDate: '2024-09-05',
  },
  {
    id: 't24',
    userId: 'u5',
    title: 'Develop user feedback system',
    summary: 'Implement a system for collecting and analyzing user feedback',
    dueDate: '2024-11-25',
  },
  {
    id: 't25',
    userId: 'u6',
    title: 'Enhance security features',
    summary: 'Upgrade security measures to protect user data and privacy',
    dueDate: '2024-12-15',
  },
  {
    id: 't26',
    userId: 'u1',
    title: 'Refactor legacy code',
    summary: 'Clean up and improve the maintainability of legacy code',
    dueDate: '2024-10-01',
  },
  {
    id: 't27',
    userId: 'u2',
    title: 'Develop API endpoints',
    summary: 'Create and test new API endpoints for additional functionality',
    dueDate: '2024-11-05',
  },
  {
    id: 't28',
    userId: 'u3',
    title: 'Integrate third-party services',
    summary: 'Add support for third-party services and APIs',
    dueDate: '2024-08-20',
  },
  {
    id: 't29',
    userId: 'u4',
    title: 'Prepare deployment checklist',
    summary:
      'Create a checklist to ensure smooth deployment of the application',
    dueDate: '2024-09-15',
  },
  {
    id: 't30',
    userId: 'u5',
    title: 'Create user personas',
    summary: 'Develop detailed user personas for better targeting and design',
    dueDate: '2024-12-10',
  },
  {
    id: 't31',
    userId: 'u6',
    title: 'Draft release notes',
    summary: 'Prepare release notes for the upcoming application version',
    dueDate: '2024-12-01',
  },
  {
    id: 't32',
    userId: 'u1',
    title: 'Conduct code review',
    summary: 'Review and provide feedback on the latest code changes',
    dueDate: '2024-11-20',
  },
  {
    id: 't33',
    userId: 'u2',
    title: 'Implement user feedback',
    summary: 'Incorporate user feedback into the next iteration of the product',
    dueDate: '2024-12-15',
  },
  {
    id: 't34',
    userId: 'u3',
    title: 'Optimize frontend performance',
    summary: 'Improve the loading speed and responsiveness of the frontend',
    dueDate: '2024-09-01',
  },
  {
    id: 't35',
    userId: 'u4',
    title: 'Create data backup plan',
    summary: 'Develop a strategy for regular data backups and recovery',
    dueDate: '2024-10-10',
  },
  {
    id: 't36',
    userId: 'u5',
    title: 'Develop notification system',
    summary: 'Create a system for sending user notifications and alerts',
    dueDate: '2024-11-20',
  },
  {
    id: 't37',
    userId: 'u6',
    title: 'Plan customer support strategy',
    summary:
      'Develop a strategy for providing customer support and handling inquiries',
    dueDate: '2024-12-25',
  },
];
